test: off
version: '0.3.{build}'
image: Visual Studio 2017

branches:
  only:
  - master
skip_tags: true

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

dotnet_csproj:
  patch: false
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{build}'
  informational_version: '{version}'
  
init:
  # Good practice, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
      
install:
  # Install repo specific stuff here

before_build:
  # Restore packages
  - cmd: msbuild /t:restore ./fbchat-sharp/fbchat-sharp.csproj
  
build_script:
  # Build project
  cmd: msbuild /t:build /p:Configuration=Release ./fbchat-sharp/fbchat-sharp.csproj

after_build:
  - cmd: nuget pack ./fbchat-sharp/fbchat-sharp.nuspec

artifacts:
  - path: '**\*.nupkg'

deploy:
  release: $(appveyor_build_version)
  description: fbchat-sharp AppVeyor build.
  provider: GitHub
  auth_token:
    secure: HzG3BylRrdqU49wZmjr6asVW70vqKv03uHai403G6PkHjpmD9s8C17IlpnxHPy8h # your encrypted token from GitHub
  artifact: /.*\.nupkg/            # upload all NuGet packages to release assets
  draft: true
  prerelease: false
  force_update: true
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: false       # deploy on tag push only (--> always)
